# Generated by Django 4.2.14 on 2024-07-30 07:13

from django.db import migrations, models
import user_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, validators=[user_app.models.validate_username])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[user_app.models.validate_email])),
                ('password', models.CharField(max_length=128)),
                ('confirm_password', models.CharField(max_length=128)),
            ],
        ),
    ]
